### PR TITLE
supply methods on the plotBin class to allow smooth json serializatio…

### PR DESCRIPTION
**Pull request by rburghol**
…n and unserialization

Hey @COBrogan and @mwdunlap2004 - this contains methods on the plotBin object that handle the serialization and unserialization seamlessly, I believe.  This is now my preferred method, but I'd like your feedback.  Essentially I created 2 new methods on the object:
- `toJSON()`: takes the objects attributes and serializes them into properly formatted json
- `fromJSON()`: takes a json text and populates the attributes of the current object with the unserialized json.

Furthermore, the `new()` method for `plotBin` is capable of accepting a json text as it's `data` argument, and when it gets such a thing, it calls it's own `fromJSON` method which unserializes and sets the attributes of the new object.

### CODE REVIEW

**Comment by COBrogan** [comment]
This is the preferable approach. I like that you can work new methods into these objects, that's pretty neat. I've never really expanded beyond base R objects, but this is cool that you can write methods so easily. This will ensure our output files are more human-readable, which will make it easier to quickly double-check outputs without having to initialize R.

**Comment by rburghol** [comment]
@COBrogan @mwdunlap2004 -- Thanks to both of you for the quick review.  I am going to put these changes into the file `lm_analysis_plots.R`, and then delete the `lm_analysis_plots_copy.R` file, so as to avoid confusion moving forward with duplicate file names.  We can let git sort it out if we make changes and then have regrets.

**Comment by mwdunlap2004** [comment]
I'm having issues with writing out our JSON, when I try to use data_from_json as our data to write out I get an error saying cat can't write out R6 objects.  However, when I use data_meth_json as the data to write out, I get issues with the formatting when I try to read it in for the residual function. 
Screenshot 2024-07-29 at 11 33 00 AM
Screenshot 2024-07-29 at 11 35 05 AM
Screenshot 2024-07-29 at 11 35 32 AM

**Comment by rburghol** [comment]
@mwdunlap2004 at a glance, the writing data_from_json should fail, since that is the data_lm object that's been reconstituted.  data_meth_json IS the correct thing to write. 

As for the second error, you need to replace your fromJSON() call in your plotting function to use the method that I demonstrated in line 41. In other words, these are six objects can neither be written to JSON or directly reconstituted from JSON using native methods, that's why I programmed those methods onto the class to handle it.

**Comment by mwdunlap2004** [comment]
Yesterday I talked with @rburghol about an issue I was having with reading in the JSON we created in the mon_lm_analysis step, for some reason, we had issues reading in the json as a txt and then converting it into data_lm. Right now, the solution we cam up with is putting the residuals step inside of our mon_lm_analysis function, that way we have the residuals from the original data, as opposed to doing it in a separate step. When I ran it this morning it did work, I created the pngs for all the months in the same function.
nldas2_01665500_residuals6
nldas2_01665500_residuals6
I will say, I was able to read in the data following the method Connor made, and create a JSON with that. Which I was able to use to make residuals, so maybe we follow that example, or we can make the residuals as a part of this function. I'm just not sure what good our JSON is going to be if we can't use it for anything because we can't read it in.

**Comment by COBrogan** [comment]
Updates here https://github.com/HARPgroup/meta_model/pull/86

**Pull request merged**
